# 1.选择文件夹

In [1]:
timing = input('am or pm: ')

am or pm: am

In [2]:
import pandas as pd
import os

In [3]:
list_file = list(os.walk('./'))[0][2]
print(list_file)

for file in list_file:
    if 'MRP' in file:
        mrp = './' + file
    elif '断货改价' in file:
        last = './' + file
    elif '改价表' in file:
        stcok = './' + file 
    elif '替代ok' in file:
        alternate = './' + file
    elif '替代update' in file:
        update = './' + file
    elif '替代料总表' in file:
        combination = './' + file
    elif '每日品类' in file:
        day_category = './' + file

print(f'MRP \t{mrp}')
print(f'last \t{last}')
print(f'stock \t{stcok}')
print(f'alternate \t{alternate}')
print(f'update \t{update}')
print(f'combination \t{combination}')
print(f'day_category \t{day_category}')

['1.替代料表整理-Bear20230724.ipynb', 'color_Bear_断货改价_Hebe_下午 8.26.xlsx', 'US MRP20230821-运营（更新）.xlsx', '大账号_(Attention) _2.ipynb', '改价表 8-28.xlsx', '替代ok表_20230824_174855.xlsx', '替代update表_20230824_174414.xlsx', '替代料总表08-22（替代料更新）.xlsx', '每日品类调价 8.26.xls']
MRP 	./US MRP20230821-运营（更新）.xlsx
last 	./color_Bear_断货改价_Hebe_下午 8.26.xlsx
stock 	./改价表 8-28.xlsx
alternate 	./替代ok表_20230824_174855.xlsx
update 	./替代update表_20230824_174414.xlsx
combination 	./替代料总表08-22（替代料更新）.xlsx
day_category 	./每日品类调价 8.26.xls

# 2.替代料表

In [4]:
df_alternate = pd.read_excel(alternate).fillna('')
df_alternate['row'] = [str(i) for i in range(len(df_alternate))]
df_alternate

,主料SKU,替换料1,替换料2,替换料3,替换料4,替换料5,替换料6,row
0,USCA171876,USCA171876-3,USCA171876D,USCA171876D-3,,,,0
1,USGS37022G,USGS37022J,USGS37022,USGS37022T,,,,1
2,USGS36761TB,USGS36761,USGS36761T,,,,,2
3,USGS41570B,USGS41570,,,,,,3
4,USGS69025S,USGS69025,USGS69025TB,USGS69025T,,,,4
...,...,...,...,...,...,...,...,...
40947,USTLA85200-C,USTLA85200,,,,,,40947
40948,USTLA89011-C,USTLA89011,,,,,,40948
40949,USWR40588-C,USWR40588,,,,,,40949
40950,USWR40589,USWR40589-C,,,,,,40950
40951,USACC11756-C,USACC11756,,,,,,40951

# 3. 计算在途总数、库存

In [5]:
# 导入改价表数据计算在途总数以及每个SKU的库存
df_stock = pd.read_excel(stcok,
                         names=['SKU', '在途总数', 'YKD库存'],
                         usecols='A,E,F'
                         ).fillna(0)
df_stock

                 SKU  在途总数  YKD库存
0         USBDA04239   0.0      4
1         USBDA04868   3.0      0
2         USDLA3ZP50   0.0      3
3         USEVC271FG   8.0      0
4         USBDA04007   0.0      1
...              ...   ...    ...
243407     USGS49820   0.0      1
243408    USWR52564C   0.0      1
243409  USCVA63523-C   0.0      2
243410  USRAD13576-C   0.0      4
243411    USOFH31050   0.0      1

[243412 rows x 3 columns]

In [6]:
# 计算自身以及-N以及-NC的库存
df_stock['SKU'] = [df_stock.loc[i, 'SKU'][:-2] if df_stock.loc[i, 'SKU'].endswith('-N') else df_stock.loc[i, 'SKU'][:-3] if df_stock.loc[i, 'SKU'].endswith('-NC') else df_stock.loc[i,'SKU'] for i in range(len(df_stock))]

# 汇总每个SKU的库存
df_stock = df_stock.groupby(df_stock['SKU'], as_index=False).sum()
df_stock

                          SKU  在途总数  YKD库存
0      BPD8550086500+BRS31318   0.0      1
1                   CAWR41163   0.0      1
2                  CS20230609   0.0      0
3                    CS230530   0.0      0
4                CSPJ20230615   0.0      1
...                       ...   ...    ...
73750          YHTWS58202-Y-6   0.0      0
73751        YHTWS5W1ZBA-Y-10   0.0      0
73752         YHTWS5W1ZBA-Y-8   0.0      0
73753          YHTWS802AA-Y-6   0.0      0
73754          YHTWS803AC-Y-3   0.0      0

[73755 rows x 3 columns]

In [7]:
# 得到每个替代料的库存数量
df_alternate['在途总数'] = 0
df_alternate['YKD库存'] = 0

df_alternate = pd.merge(left=df_alternate, right=df_stock, how='left', left_on='主料SKU', right_on='SKU', suffixes=('','_0')).fillna(0)
df_alternate = pd.merge(left=df_alternate, right=df_stock, how='left', left_on='替换料1', right_on='SKU', suffixes=('','_1')).fillna(0)
df_alternate = pd.merge(left=df_alternate, right=df_stock, how='left', left_on='替换料2', right_on='SKU', suffixes=('','_2')).fillna(0)
df_alternate = pd.merge(left=df_alternate, right=df_stock, how='left', left_on='替换料3', right_on='SKU', suffixes=('','_3')).fillna(0)
df_alternate = pd.merge(left=df_alternate, right=df_stock, how='left', left_on='替换料4', right_on='SKU', suffixes=('','_4')).fillna(0)
df_alternate = pd.merge(left=df_alternate, right=df_stock, how='left', left_on='替换料5', right_on='SKU', suffixes=('','_5')).fillna(0)
df_alternate = pd.merge(left=df_alternate, right=df_stock, how='left', left_on='替换料6', right_on='SKU', suffixes=('','_6')).fillna(0)
df_alternate

,主料SKU,替换料1,替换料2,替换料3,替换料4,替换料5,替换料6,row,在途总数,YKD库存,...,YKD库存_3,SKU_4,在途总数_4,YKD库存_4,SKU_5,在途总数_5,YKD库存_5,SKU_6,在途总数_6,YKD库存_6
0,USCA171876,USCA171876-3,USCA171876D,USCA171876D-3,,,,0,0,0,...,12.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0
1,USGS37022G,USGS37022J,USGS37022,USGS37022T,,,,1,0,0,...,19.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0
2,USGS36761TB,USGS36761,USGS36761T,,,,,2,0,0,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0
3,USGS41570B,USGS41570,,,,,,3,0,0,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0
4,USGS69025S,USGS69025,USGS69025TB,USGS69025T,,,,4,0,0,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40947,USTLA85200-C,USTLA85200,,,,,,40947,0,0,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0
40948,USTLA89011-C,USTLA89011,,,,,,40948,0,0,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0
40949,USWR40588-C,USWR40588,,,,,,40949,0,0,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0
40950,USWR40589,USWR40589-C,,,,,,40950,0,0,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0
40951,USACC11756-C,USACC11756,,,,,,40951,0,0,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0

In [8]:
df_alternate.columns

Index(['主料SKU', '替换料1', '替换料2', '替换料3', '替换料4', '替换料5', '替换料6', 'row', '在途总数',
       'YKD库存', 'SKU', '在途总数_0', 'YKD库存_0', 'SKU_1', '在途总数_1', 'YKD库存_1',
       'SKU_2', '在途总数_2', 'YKD库存_2', 'SKU_3', '在途总数_3', 'YKD库存_3', 'SKU_4',
       '在途总数_4', 'YKD库存_4', 'SKU_5', '在途总数_5', 'YKD库存_5', 'SKU_6', '在途总数_6',
       'YKD库存_6'],
      dtype='object')

In [9]:
# 计算每个替代料的“在途总数”以及”替代料库存“
df_alternate['在途总数'] = df_alternate['在途总数_0'] + df_alternate['在途总数_1'] + df_alternate['在途总数_2'] + df_alternate['在途总数_3'] + df_alternate['在途总数_4'] + df_alternate['在途总数_5'] + df_alternate['在途总数_6'] 

df_alternate['YKD库存'] = df_alternate['YKD库存_0'] + df_alternate['YKD库存_1'] + df_alternate['YKD库存_2'] + df_alternate['YKD库存_3'] + df_alternate['YKD库存_4'] + df_alternate['YKD库存_5'] + df_alternate['YKD库存_6'] 

df_alternate = df_alternate[['主料SKU',
                           '替换料1',
                           '替换料2',
                           '替换料3',
                           '替换料4',
                           '替换料5',
                           '替换料6',
                           '在途总数',
                           'YKD库存',
                           'row']].copy()
df_alternate

,主料SKU,替换料1,替换料2,替换料3,替换料4,替换料5,替换料6,在途总数,YKD库存,row
0,USCA171876,USCA171876-3,USCA171876D,USCA171876D-3,,,,6.0,12.0,0
1,USGS37022G,USGS37022J,USGS37022,USGS37022T,,,,12.0,20.0,1
2,USGS36761TB,USGS36761,USGS36761T,,,,,4.0,4.0,2
3,USGS41570B,USGS41570,,,,,,23.0,99.0,3
4,USGS69025S,USGS69025,USGS69025TB,USGS69025T,,,,6.0,34.0,4
...,...,...,...,...,...,...,...,...,...,...
40947,USTLA85200-C,USTLA85200,,,,,,10.0,0.0,40947
40948,USTLA89011-C,USTLA89011,,,,,,10.0,0.0,40948
40949,USWR40588-C,USWR40588,,,,,,6.0,0.0,40949
40950,USWR40589,USWR40589-C,,,,,,6.0,0.0,40950
40951,USACC11756-C,USACC11756,,,,,,19.0,0.0,40951

In [10]:
list_tmp = []

for i in df_alternate.columns[:-3]:
    df_tmp = df_alternate[[i,
                          '在途总数',
                          'YKD库存',
                          'row']]
    df_tmp.columns = ['SKU','在途总数', 'YKD库存', 'row']
    df_tmp = df_tmp[df_tmp['SKU'] != '']
    list_tmp.append(df_tmp)
    
df_position = pd.concat(list_tmp).reset_index(drop=True)
df_position

                   SKU  在途总数  YKD库存    row
0           USCA171876   6.0   12.0      0
1           USGS37022G  12.0   20.0      1
2          USGS36761TB   4.0    4.0      2
3           USGS41570B  23.0   99.0      3
4           USGS69025S   6.0   34.0      4
...                ...   ...    ...    ...
86804    USGS27875GB-C   6.0    3.0  21816
86805  USGS16178GNZB-C   2.0    0.0  22508
86806     USGS6310TNZB   0.0   25.0  22784
86807       USIC2A366Z   0.0    1.0  36705
86808       USIC04470I   0.0    4.0  36803

[86809 rows x 4 columns]

In [11]:
df_stock = pd.concat([df_position,df_stock]).drop_duplicates(['SKU'], keep='first').reset_index(drop=True).fillna('')
df_stock

                     SKU  在途总数  YKD库存 row
0             USCA171876   6.0   12.0   0
1             USGS37022G  12.0   20.0   1
2            USGS36761TB   4.0    4.0   2
3             USGS41570B  23.0   99.0   3
4             USGS69025S   6.0   34.0   4
...                  ...   ...    ...  ..
108463    YHTWS58202-Y-6   0.0    0.0
108464  YHTWS5W1ZBA-Y-10   0.0    0.0
108465   YHTWS5W1ZBA-Y-8   0.0    0.0
108466    YHTWS802AA-Y-6   0.0    0.0
108467    YHTWS803AC-Y-3   0.0    0.0

[108468 rows x 4 columns]

In [12]:
df_stock_way = df_stock[['SKU', '在途总数']]
df_stock_way

                     SKU  在途总数
0             USCA171876   6.0
1             USGS37022G  12.0
2            USGS36761TB   4.0
3             USGS41570B  23.0
4             USGS69025S   6.0
...                  ...   ...
108463    YHTWS58202-Y-6   0.0
108464  YHTWS5W1ZBA-Y-10   0.0
108465   YHTWS5W1ZBA-Y-8   0.0
108466    YHTWS802AA-Y-6   0.0
108467    YHTWS803AC-Y-3   0.0

[108468 rows x 2 columns]

In [13]:
df_stock = df_stock[['SKU', 'YKD库存', 'row']].copy()
df_stock['总库存'] = df_stock['YKD库存']
df_stock.loc[:,'组合料库存'] = 0
df_stock = df_stock[['SKU',
                     '组合料库存',
                     'YKD库存',
                     '总库存',
                     'row']]
df_stock

                     SKU  组合料库存  YKD库存   总库存 row
0             USCA171876      0   12.0  12.0   0
1             USGS37022G      0   20.0  20.0   1
2            USGS36761TB      0    4.0   4.0   2
3             USGS41570B      0   99.0  99.0   3
4             USGS69025S      0   34.0  34.0   4
...                  ...    ...    ...   ...  ..
108463    YHTWS58202-Y-6      0    0.0   0.0
108464  YHTWS5W1ZBA-Y-10      0    0.0   0.0
108465   YHTWS5W1ZBA-Y-8      0    0.0   0.0
108466    YHTWS802AA-Y-6      0    0.0   0.0
108467    YHTWS803AC-Y-3      0    0.0   0.0

[108468 rows x 5 columns]

# 3.2 组合料库存

In [14]:
# 从替代料总表中读取组合料关系，去除数量为0，为1，为空的情况
df_combination = pd.read_excel(combination,
                               header=1,
                               dtype={'数量':str})[['主料SKU','数量','SKU1','SKU2','SKU3','SKU4','SKU5']].fillna('')

df_combination = df_combination[(df_combination['数量'] != '0') & (df_combination['数量'] != '1') & (df_combination['数量'] != '')].reset_index(drop=True)

df_combination

,主料SKU,数量,SKU1,SKU2,SKU3,SKU4,SKU5
0,USCA171876D-3,1+1+1,USCA51317D,USCA51318D,USCAB3376D,,
1,USWCP52105-2,1+1,USWCP02525,USWCP05210,,,
2,USGS00429LR,1+1,USGS00429-1,USGS03029-1,,,
3,USGS69015TLR,1+1,USGS69015TL-1,USGS69015TR-1,,,
4,USSKA98377LR,1+1,USSKA98376,USSKA98377,,,
...,...,...,...,...,...,...,...
4434,USBRPR721486FR,1+1+1+1,USBPD10860,USBPD91400,USBRR31347,USBRR31372,
4435,USBRPR581465FR,1+1+1+1,USBPD86500,USBPD91400,USBRR31275,USBRR31318,
4436,USBRPS46315,1+1,USBPD815A0,USBRS31463,,,
4437,USBRPS091505FR,1+1+1+1,USBPD815A0,USBPD90500,USBRS31349,USBRS31350,
4438,USBRPR091505FR,1+1+1+1,USBPD815A0,USBPD90500,USBRR31349,USBRR31350,

In [15]:
def DEduplicate(df):
    list_row = list(set(df['row'].tolist()))
    if '' in list_row:
        list_row.remove('')
    list_row.sort()
    
    dict_row = {}
    for row in list_row:
        dict_row[row] = ''
    for i in range(len(df)):
        if df.loc[i, 'row'] != '':
            dict_row[df.loc[i, 'row']] += str(i) + ';'
    
    list_duplicated = []
    for i in dict_row:
        list_row = dict_row[i].split(';')[:-1]
        list_row.sort()
        length = len(list_row)
        if length > 1:
            for j in range(length -1):
                list_duplicated.append(list_row[j])
                
    for i in list_duplicated:
        df = df.drop(int(i))
        
    return df.reset_index(drop=True),list_duplicated

In [16]:
# 左连接获得替代料关系原来的行位置，如果有重复则删除
df_combination = pd.merge(left=df_combination, right=df_position, how='left', left_on='主料SKU', right_on='SKU', suffixes=('','_0')).fillna('')
df_combination,l = DEduplicate(df_combination)

print(list(df_combination.columns))
df_combination

['主料SKU', '数量', 'SKU1', 'SKU2', 'SKU3', 'SKU4', 'SKU5', 'SKU', '在途总数', 'YKD库存', 'row']

,主料SKU,数量,SKU1,SKU2,SKU3,SKU4,SKU5,SKU,在途总数,YKD库存,row
0,USCA171876D-3,1+1+1,USCA51317D,USCA51318D,USCAB3376D,,,USCA171876D-3,6.0,12.0,0
1,USWCP52105-2,1+1,USWCP02525,USWCP05210,,,,,,,
2,USGS00429LR,1+1,USGS00429-1,USGS03029-1,,,,USGS00429LR,42.0,70.0,5
3,USGS69015TLR,1+1,USGS69015TL-1,USGS69015TR-1,,,,USGS69015TLR,5.0,14.0,17
4,USSKA98377LR,1+1,USSKA98376,USSKA98377,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...
4434,USBRPR721486FR,1+1+1+1,USBPD10860,USBPD91400,USBRR31347,USBRR31372,,,,,
4435,USBRPR581465FR,1+1+1+1,USBPD86500,USBPD91400,USBRR31275,USBRR31318,,,,,
4436,USBRPS46315,1+1,USBPD815A0,USBRS31463,,,,,,,
4437,USBRPS091505FR,1+1+1+1,USBPD815A0,USBPD90500,USBRS31349,USBRS31350,,,,,
4438,USBRPR091505FR,1+1+1+1,USBPD815A0,USBPD90500,USBRR31349,USBRR31350,,,,,

In [17]:
# 获得组合料每个SKU对应的库存
df_combination = pd.merge(left=df_combination, right=df_stock, how='left', left_on='SKU1', right_on='SKU', suffixes=('','_1')).fillna({'YKD库存_1':0})
df_combination = pd.merge(left=df_combination, right=df_stock, how='left', left_on='SKU2', right_on='SKU', suffixes=('','_2')).fillna({'YKD库存_2':0})
df_combination = pd.merge(left=df_combination, right=df_stock, how='left', left_on='SKU3', right_on='SKU', suffixes=('','_3')).fillna({'YKD库存_3':0})
df_combination = pd.merge(left=df_combination, right=df_stock, how='left', left_on='SKU4', right_on='SKU', suffixes=('','_4')).fillna({'YKD库存_4':0})
df_combination = pd.merge(left=df_combination, right=df_stock, how='left', left_on='SKU5', right_on='SKU', suffixes=('','_5')).fillna({'YKD库存_5':0})
df_combination

,主料SKU,数量,SKU1,SKU2,SKU3,SKU4,SKU5,SKU,在途总数,YKD库存,...,SKU_4,组合料库存_4,YKD库存_4,总库存_4,row_4,SKU_5,组合料库存_5,YKD库存_5,总库存_5,row_5
0,USCA171876D-3,1+1+1,USCA51317D,USCA51318D,USCAB3376D,,,USCA171876D-3,6.0,12.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
1,USWCP52105-2,1+1,USWCP02525,USWCP05210,,,,,,,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
2,USGS00429LR,1+1,USGS00429-1,USGS03029-1,,,,USGS00429LR,42.0,70.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
3,USGS69015TLR,1+1,USGS69015TL-1,USGS69015TR-1,,,,USGS69015TLR,5.0,14.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
4,USSKA98377LR,1+1,USSKA98376,USSKA98377,,,,,,,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4434,USBRPR721486FR,1+1+1+1,USBPD10860,USBPD91400,USBRR31347,USBRR31372,,,,,...,USBRR31372,0.0,4.0,4.0,,NaN,NaN,0.0,NaN,NaN
4435,USBRPR581465FR,1+1+1+1,USBPD86500,USBPD91400,USBRR31275,USBRR31318,,,,,...,USBRR31318,0.0,6.0,6.0,,NaN,NaN,0.0,NaN,NaN
4436,USBRPS46315,1+1,USBPD815A0,USBRS31463,,,,,,,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
4437,USBRPS091505FR,1+1+1+1,USBPD815A0,USBPD90500,USBRS31349,USBRS31350,,,,,...,USBRS31350,0.0,8.0,8.0,,NaN,NaN,0.0,NaN,NaN
4438,USBRPR091505FR,1+1+1+1,USBPD815A0,USBPD90500,USBRR31349,USBRR31350,,,,,...,USBRR31350,0.0,5.0,5.0,,NaN,NaN,0.0,NaN,NaN

In [18]:
df_combination.columns

Index(['主料SKU', '数量', 'SKU1', 'SKU2', 'SKU3', 'SKU4', 'SKU5', 'SKU', '在途总数',
       'YKD库存', 'row', 'SKU_1', '组合料库存', 'YKD库存_1', '总库存', 'row_1', 'SKU_2',
       '组合料库存_2', 'YKD库存_2', '总库存_2', 'row_2', 'SKU_3', '组合料库存_3', 'YKD库存_3',
       '总库存_3', 'row_3', 'SKU_4', '组合料库存_4', 'YKD库存_4', '总库存_4', 'row_4',
       'SKU_5', '组合料库存_5', 'YKD库存_5', '总库存_5', 'row_5'],
      dtype='object')

In [19]:
# 计算组合料库存，根据“数量”关系来计算
import math

df_combination['组合料库存'] = 0
for i in range(len(df_combination)):
    list_amount_number = df_combination.loc[i, '数量'].split('+')
    list_amount_stock = []
    for j in range(len(list_amount_number)):
        list_amount_stock.append(df_combination.loc[i, 'YKD库存_'+str(j+1)] / int(list_amount_number[j]))
    df_combination.loc[i, '组合料库存'] = math.floor(min(list_amount_stock))
    
print(list(df_combination.columns))
df_combination

['主料SKU', '数量', 'SKU1', 'SKU2', 'SKU3', 'SKU4', 'SKU5', 'SKU', '在途总数', 'YKD库存', 'row', 'SKU_1', '组合料库存', 'YKD库存_1', '总库存', 'row_1', 'SKU_2', '组合料库存_2', 'YKD库存_2', '总库存_2', 'row_2', 'SKU_3', '组合料库存_3', 'YKD库存_3', '总库存_3', 'row_3', 'SKU_4', '组合料库存_4', 'YKD库存_4', '总库存_4', 'row_4', 'SKU_5', '组合料库存_5', 'YKD库存_5', '总库存_5', 'row_5']

,主料SKU,数量,SKU1,SKU2,SKU3,SKU4,SKU5,SKU,在途总数,YKD库存,...,SKU_4,组合料库存_4,YKD库存_4,总库存_4,row_4,SKU_5,组合料库存_5,YKD库存_5,总库存_5,row_5
0,USCA171876D-3,1+1+1,USCA51317D,USCA51318D,USCAB3376D,,,USCA171876D-3,6.0,12.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
1,USWCP52105-2,1+1,USWCP02525,USWCP05210,,,,,,,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
2,USGS00429LR,1+1,USGS00429-1,USGS03029-1,,,,USGS00429LR,42.0,70.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
3,USGS69015TLR,1+1,USGS69015TL-1,USGS69015TR-1,,,,USGS69015TLR,5.0,14.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
4,USSKA98377LR,1+1,USSKA98376,USSKA98377,,,,,,,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4434,USBRPR721486FR,1+1+1+1,USBPD10860,USBPD91400,USBRR31347,USBRR31372,,,,,...,USBRR31372,0.0,4.0,4.0,,NaN,NaN,0.0,NaN,NaN
4435,USBRPR581465FR,1+1+1+1,USBPD86500,USBPD91400,USBRR31275,USBRR31318,,,,,...,USBRR31318,0.0,6.0,6.0,,NaN,NaN,0.0,NaN,NaN
4436,USBRPS46315,1+1,USBPD815A0,USBRS31463,,,,,,,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN
4437,USBRPS091505FR,1+1+1+1,USBPD815A0,USBPD90500,USBRS31349,USBRS31350,,,,,...,USBRS31350,0.0,8.0,8.0,,NaN,NaN,0.0,NaN,NaN
4438,USBRPR091505FR,1+1+1+1,USBPD815A0,USBPD90500,USBRR31349,USBRR31350,,,,,...,USBRR31350,0.0,5.0,5.0,,NaN,NaN,0.0,NaN,NaN

In [20]:
df_combination = df_combination[['主料SKU',
                                 '组合料库存',
                                ]].copy()
df_combination = pd.merge(left=df_combination, right=df_position, how='left', left_on='主料SKU', right_on='SKU').fillna({'YKD库存':0, '在途总数':0,  'row':''})
df_combination

               主料SKU  组合料库存            SKU  在途总数  YKD库存 row
0      USCA171876D-3      0  USCA171876D-3   6.0   12.0   0
1       USWCP52105-2      0            NaN   0.0    0.0
2        USGS00429LR      0    USGS00429LR  42.0   70.0   5
3       USGS69015TLR      0   USGS69015TLR   5.0   14.0  17
4       USSKA98377LR      0            NaN   0.0    0.0
...              ...    ...            ...   ...    ...  ..
4434  USBRPR721486FR      0            NaN   0.0    0.0
4435  USBRPR581465FR      0            NaN   0.0    0.0
4436     USBRPS46315      1            NaN   0.0    0.0
4437  USBRPS091505FR      1            NaN   0.0    0.0
4438  USBRPR091505FR      1            NaN   0.0    0.0

[4439 rows x 6 columns]

In [21]:
# 根据辅助列row来区分是否有重复的替代料关系需要合并计算库存，所以要区分开row为空以及不为空的情况
df_combination_1 = df_combination[df_combination.loc[:, 'row']==''].copy()
df_combination_1['总库存'] = df_combination_1.loc[:, '组合料库存'] + df_combination_1.loc[:, 'YKD库存']
df_combination_1 = df_combination_1[['主料SKU',
                                     '组合料库存',
                                     'YKD库存',
                                     '总库存',
                                     'row']].reset_index(drop=True).copy()

df_combination_1.columns = ['SKU', '组合料库存','YKD库存','总库存', 'row']
df_combination_1

                 SKU  组合料库存  YKD库存   总库存 row
0       USWCP52105-2      0    0.0   0.0
1       USSKA98377LR      0    0.0   0.0
2       USSKA98407LR     20    0.0  20.0
3         USGS4549LR      0    0.0   0.0
4       USSKA98383LR     16    0.0  16.0
...              ...    ...    ...   ...  ..
2112  USBRPR721486FR      0    0.0   0.0
2113  USBRPR581465FR      0    0.0   0.0
2114     USBRPS46315      1    0.0   1.0
2115  USBRPS091505FR      1    0.0   1.0
2116  USBRPR091505FR      1    0.0   1.0

[2117 rows x 5 columns]

In [22]:
def custom_agg(row_column):
    # 检查是否有字符串或空值，如果有，返回第一个非空字符串，否则返回空字符串
    non_empty_strings = row_column.dropna().astype(str)
    if len(non_empty_strings) > 0:
        return non_empty_strings.iloc[0]
    else:
        return ''

In [23]:
df_s = pd.concat([df_stock, df_combination_1]).reset_index(drop=True).fillna('')

df_s = df_s.groupby(df_s['SKU'], as_index=False).agg({
     '组合料库存':'sum',
     'YKD库存':'sum',
     '总库存': 'sum',             
     'row': custom_agg             
})
df_s

                           SKU  组合料库存  YKD库存  总库存 row
0       BPD8550086500+BRS31318      0    1.0  1.0
1                    CAWR41163      0    1.0  1.0
2                   CS20230609      0    0.0  0.0
3                     CS230530      0    0.0  0.0
4                 CSPJ20230615      0    1.0  1.0
...                        ...    ...    ...  ...  ..
108463          YHTWS58202-Y-6      0    0.0  0.0
108464        YHTWS5W1ZBA-Y-10      0    0.0  0.0
108465         YHTWS5W1ZBA-Y-8      0    0.0  0.0
108466          YHTWS802AA-Y-6      0    0.0  0.0
108467          YHTWS803AC-Y-3      0    0.0  0.0

[108468 rows x 5 columns]

In [24]:
df_combination_2 = df_combination[df_combination.loc[:, 'row']!=''][['组合料库存',
                                                                    'row']]
df_combination_2.reset_index(drop=True)

      组合料库存    row
0         0      0
1         0      5
2         0     17
3         0     28
4         0     40
...     ...    ...
2317      0  37470
2318      0  37472
2319      0  37473
2320      0  38649
2321      0  39931

[2322 rows x 2 columns]

In [25]:
df_s = pd.merge(left=df_s, right=df_combination_2, how='left', left_on='row', right_on='row', suffixes=('','_x')).fillna(0)
df_s['总库存'] = df_s.loc[:, 'YKD库存'] + df_s.loc[:, '组合料库存'] + df_s.loc[:, '组合料库存_x']
df_s['组合料库存'] = df_s.loc[:, '组合料库存'] + df_s.loc[:, '组合料库存_x']
df_s

                           SKU  组合料库存  YKD库存  总库存 row  组合料库存_x
0       BPD8550086500+BRS31318    0.0    1.0  1.0          0.0
1                    CAWR41163    0.0    1.0  1.0          0.0
2                   CS20230609    0.0    0.0  0.0          0.0
3                     CS230530    0.0    0.0  0.0          0.0
4                 CSPJ20230615    0.0    1.0  1.0          0.0
...                        ...    ...    ...  ...  ..      ...
108463          YHTWS58202-Y-6    0.0    0.0  0.0          0.0
108464        YHTWS5W1ZBA-Y-10    0.0    0.0  0.0          0.0
108465         YHTWS5W1ZBA-Y-8    0.0    0.0  0.0          0.0
108466          YHTWS802AA-Y-6    0.0    0.0  0.0          0.0
108467          YHTWS803AC-Y-3    0.0    0.0  0.0          0.0

[108468 rows x 6 columns]

In [26]:
df_s = df_s[['SKU',
             '组合料库存',
             'YKD库存',
             '总库存']].copy()
df_stock = df_s
df_stock

                           SKU  组合料库存  YKD库存  总库存
0       BPD8550086500+BRS31318    0.0    1.0  1.0
1                    CAWR41163    0.0    1.0  1.0
2                   CS20230609    0.0    0.0  0.0
3                     CS230530    0.0    0.0  0.0
4                 CSPJ20230615    0.0    1.0  1.0
...                        ...    ...    ...  ...
108463          YHTWS58202-Y-6    0.0    0.0  0.0
108464        YHTWS5W1ZBA-Y-10    0.0    0.0  0.0
108465         YHTWS5W1ZBA-Y-8    0.0    0.0  0.0
108466          YHTWS802AA-Y-6    0.0    0.0  0.0
108467          YHTWS803AC-Y-3    0.0    0.0  0.0

[108468 rows x 4 columns]

# 4.MRP表整理

In [27]:
# 导入MRP数据，整合后续的断货改价表
df_mrp = pd.read_excel(mrp,
                       header=1,
                       names=['SKU','品类','层级','身份','负责人'],
                       usecols='B,G,H,J,AR')
df_mrp

                     SKU   品类     层级  身份    负责人
0      USTCV17215HIE-2-C  TCV   TOP1  老品    Ada
1           USTBC40007-C  TBC   TOP1  老品  Rosie
2         USBDA04108-2-C  BDA   TOP1  老品    Ada
3           USET87039H-C   ET   TOP1  老品    Ada
4           USGSM3570T-C   GS  TOP10  老品    Ada
...                  ...  ...    ...  ..    ...
56520  USWSP65508B1-2-YC  WSP     普通  新品   Hebe
56521  USWSP54521B1-4-YC  WSP  TOP20  新品   Hebe
56522  USWSP54717B1-4-YC  WSP     普通  新品   Hebe
56523  USWSP54717B1-2-YC  WSP     普通  新品   Hebe
56524       USACC11756-C  ACC  TOP10  新品    Ada

[56525 rows x 5 columns]

In [28]:
# 筛选除CA品类以及CA-的品类都是Hebe负责的
import pandas as pd

hebe = ['CA' if category[:3] == 'CA-' else category if category=='CA' else category for category in df_mrp.loc[:, '品类']]

hebe

['TCV',
 'TBC',
 'BDA',
 'ET',
 'GS',
 'FP',
 'BM',
 'OP',
 'BM',
 'PSS',
 'OC',
 'BMR',
 'IF',
 'ABS',
 'WP',
 'PHLS',
 'BC',
 'FP',
 'WR',
 'WR',
 'EAF',
 'BMR',
 'SG',
 'WS',
 'TPMS',
 'TPMS',
 'FSU',
 'CAF',
 'BM',
 'GS',
 'IM',
 'THB',
 'WR',
 'ET',
 'WS',
 'CVA',
 'CS-弹簧',
 'ABS',
 'GS',
 'GS',
 'OS',
 'SG',
 'WS',
 'SBB',
 'STR',
 'ABS',
 'BC',
 'CCS',
 'DS',
 'GS',
 'SG',
 'CVA',
 'CAF',
 'HVCP',
 'TBC',
 'ACC',
 'BDA',
 'FP',
 'GS',
 'GS',
 'SG',
 'SG',
 'DIF',
 'TPMS',
 'ACC',
 'CON',
 'ALT',
 'GS',
 'GS',
 'CAF',
 'BDA',
 'ABS',
 'BC',
 'BC',
 'DHC',
 'DLA',
 'FP',
 'FP',
 'HB',
 'IC',
 'PSP',
 'TF',
 'WP',
 'WR',
 'THB',
 'CPS',
 'BC',
 'HBZ',
 'TSS',
 'PBB',
 'PSS',
 'KS',
 'ICK',
 'OFA',
 'BMC',
 'WGA',
 'EAF',
 'CAF',
 'AFB',
 'BC',
 'BC',
 'BC',
 'BM',
 'BT',
 'CPS',
 'DIS',
 'FFA',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'GS',
 'GS',
 'GS',
 'GS',
 'HB',
 'HM',
 'HM',
 'IC',
 'PSR',
 'REL',
 'SG',
 'SKA',
 'ABS',
 'DLA',
 'ABS',
 'TCK',
 'DAM',
 'ACH',
 'CON',
 'STR',
 'ICK',
 'CON',
 'HM',
 'RAD',
 'SA',
 'MAF',
 'TF',
 'FI',
 'MI',
 'CAF',
 'ABS',
 'ACC',
 'BC',
 'BC',
 'BC',
 'BDA',
 'BM',
 'BM',
 'BM',
 'BM',
 'BM',
 'BM',
 'BM',
 'CA',
 'DLA',
 'DLA',
 'FP',
 'FP',
 'GS',
 'GS',
 'GS',
 'GS',
 'HB',
 'IC',
 'IC',
 'OFA',
 'OS',
 'OS',
 'OS',
 'OS',
 'PHLS',
 'PSP',
 'SG',
 'WM',
 'WP',
 'ABS',
 'WIM',
 'WP',
 'BC',
 'STW',
 'STW',
 'THK',
 'FP',
 'FP',
 'ICK',
 'MAF',
 'SKA',
 'ACV',
 'BDA',
 'PBB',
 'ILH',
 'RASA',
 'CS-弹簧',
 'KS',
 'CON',
 'AS',
 'ICK',
 'CA',
 'WP',
 'HB',
 'FI',
 'BHH',
 'EAF',
 'CAF',
 'TCV',
 'CAF',
 'ABS',
 'ABS',
 'ABS',
 'ACC',
 'ACC',
 'ACC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BDA',
 'BDA',
 'BM',
 'BM',
 'BM',
 'BMR',
 'BMR',
 'CPS',
 'DLA',
 'DLA',
 'DLA',
 'DLA',
 'ET',
 'ET',
 'ET',
 'ET',
 'ET',
 'EVC',
 'FFP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'GS',
 'HB',
 'IC',
 'IC',
 'IC',
 'IC',
 'IC',
 'LGH',
 'OS',
 'OS',
 'PSP',
 'THA',
 'TLA',
 'TPS',
 'TS',
 'WR',
 'WR',
 'WR',
 'WL',
 'IC',
 'SKA',
 'ABS',
 'ABS',
 'HB',
 'HB',
 'ET',
 'BC',
 'TCK',
 'WS',
 'SBB',
 'DAM',
 'DAM',
 'TCK',
 'ICK',
 'ICK',
 'THB',
 'MAF',
 'PSR',
 'FTS',
 'OLS',
 'WIM',
 'PSS',
 'TBC',
 'TPMS',
 'TPMS',
 'TPMS',
 'AEV',
 'CS-弹簧',
 'KS',
 'WR',
 'WR',
 'ICK',
 'ACC',
 'CON',
 'CON',
 'STR',
 'ICK',
 'ICK',
 'STR',
 'STR',
 'CA',
 'STR',
 'STR',
 'ICK',
 'ICK',
 'CA',
 'CON',
 'BMC',
 'PSH',
 'PSH',
 'TMS',
 'FI',
 'FI',
 'MI',
 'EAF',
 'CAF',
 'EVC',
 'HL',
 'CAF',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ACC',
 'ACC',
 'ACC',
 'ACC',
 'ACC',
 'ACC',
 'AFB',
 'ASC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BDA',
 'BDA',
 'BDA',
 'BLS',
 'BM',
 'BM',
 'BM',
 'BM',
 'BM',
 'BMR',
 'BMR',
 'BMR',
 'BMR',
 'BMR',
 'CA',
 'CA',
 'CA',
 'CA',
 'CA',
 'CA',
 'CPS',
 'CPS',
 'CPS',
 'CPS',
 'DLA',
 'DLA',
 'DLA',
 'DLA',
 'DLA',
 'DLA',
 'DS',
 'DS',
 'EVC',
 'FFA',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FTS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'HB',
 'HM',
 'HM',
 'HWN',
 'IC',
 'IC',
 'IC',
 'IC',
 'IC',
 'OFH',
 'OS',
 'OS',
 'PHLS',
 'PHLS',
 'PHLS',
 'PS',
 'PS',
 'PS',
 'SG',
 'SG',
 'SG',
 'SG',
 'SKA',
 'SKA',
 'TCM',
 'THB',
 'TS',
 'WIM',
 'WIM',
 'WIM',
 'WR',
 'WR',
 'WR',
 'WS',
 'WS',
 'IC',
 'SKA',
 'ABS',
 'ABS',
 'WR',
 'WP',
 'WP',
 'CS-弹簧',
 'ABS',
 'WM',
 'HB',
 'FP',
 'STW',
 'WR',
 'SBB',
 'APT',
 'DAM',
 'BC',
 'KS',
 'MAF',
 'SA',
 'ICK',
 'WR',
 'SKA',
 'HBZ',
 'ABS',
 'AGSA',
 'ACH',
 'CVA',
 'TBC',
 'WIM',
 'TBC',
 'TBC',
 'TBC',
 'TCV',
 'ASV',
 'HS',
 'TPMS',
 'AEV',
 'CS-弹簧',
 'OIP',
 'BPS',
 'BPS',
 'HCR',
 'KS',
 'WR',
 'BPS',
 'KS',
 'ACC',
 'ACC',
 'CON',
 'CON',
 'CON',
 'CON',
 'CON',
 'ALT',
 'DAM',
 'CA',
 'CA',
 'CA',
 'OFA',
 'CA',
 'CON',
 'CON',
 'WDC',
 'FP',
 'WP',
 'BMC',
 'BMC',
 'CA',
 'RAD',
 'RAD',
 'GS',
 'BRS',
 'BPD',
 'BPD',
 'CA',
 'CA',
 'SA',
 'BMC',
 'DLPK',
 'TF',
 'TF',
 'TF',
 'TF',
 'BHH',
 'CSA',
 'FP',
 'WR',
 'FIK',
 'DLA',
 'DIF',
 'BHH',
 'EAF',
 'SG',
 'CST',
 'CST',
 'CAF',
 'CAF',
 'CA',
 'CAF',
 'CAF',
 'CAF',
 'CAF',
 'CAF',
 'CAF',
 'BDA',
 'ORV',
 'DS',
 'ACC',
 'SCS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ACC',
 'ACC',
 'ACC',
 'ACC',
 'ACC',
 'ACC',
 'ACC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BC',
 'BDA',
 'BDA',
 'BDA',
 'BDA',
 'BDA',
 'BDA',
 'BDA',
 'BDS',
 'BM',
 'BM',
 'BM',
 'BM',
 'BM',
 'BM',
 'BM',
 'BM',
 'BM',
 'BT',
 'CA',
 'CA',
 'CA',
 'CA',
 'CA',
 'CA',
 'CA',
 'CA',
 'CPS',
 'CPS',
 'CPS',
 'CPS',
 'CPS',
 'DLA',
 'DLA',
 'DLA',
 'DLA',
 'DLA',
 'DLA',
 'DS',
 'DS',
 'DS',
 'ET',
 'ET',
 'ET',
 'ET',
 'ET',
 'ET',
 'EVC',
 'EVC',
 'EVC',
 'EVC',
 'FB',
 'FC',
 'FFA',
 'FFP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'FP',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'GS',
 'HB',
 'HB',
 'HB',
 'HCM',
 'IC',
 'IC',
 'IC',
 'IC',
 'IC',
 'IC',
 'IC',
 'IC',
 'IC',
 'IC',
 'IM',
 'IM',
 'KS',
 'KS',
 'KS',
 'LCM',
 'OFA',
 'OFH',
 'OP',
 'OS',
 'OS',
 'OS',
 'OS',
 'OS',
 'OS',
 'OS',
 'OS',
 'OS',
 'OS',
 'OS',
 'OS',
 'OS',
 'PHLS',
 'PHLS',
 'PS',
 'PSP',
 'PSP',
 'PSP',
 'PSP',
 'PSR',
 'SG',
 'SG',
 'SG',
 'SG',
 'SG',
 'SKA',
 'SKA',
 'SKA',
 'SKA',
 'SKA',
 'SKA',
 'SS',
 'TCV',
 'TCV',
 'THB',
 'TPS',
 'VLT',
 'WIM',
 'WIM',
 'WM',
 'WM',
 'WP',
 'WP',
 'WR',
 'WR',
 'WR',
 'WR',
 'WR',
 'WR',
 'WR',
 'WR',
 'WR',
 'WR',
 'WS',
 'WS',
 'WS',
 'WS',
 'WL',
 'FTS',
 'WR',
 'ABS',
 'ABS',
 'ABS',
 'DS',
 'ACC',
 'BC',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'ABS',
 'GS',
 'BC',
 'BC',
 'EM',
 'EM',
 'EM',
 'EM',
 'PSP',
 'CMPS',
 'SS',
 'FI',
 'HB',
 'HB',
 'HB',
 'FB',
 'STW',
 'STW',
 'WR',
 'CHC',
 'CHC',
 'CHC',
 'WS',
 'WS',
 'HMB',
 'SBB',
 'DHH',
 'TCK',
 'FP',
 'DS',
 'ICK',
 'SRM',
 'MAF',
 'SA',
 'RBD',
 'ICK',
 'SKA',
 'THB',
 'HBZ',
 'HBZ',
 'HBZ',
 'WR',
 'OC',
 'CVA',
 'CVA',
 'ACH',
 'ACH',
 'ACH',
 'ACH',
 'ACH',
 'ACH',
 'ACH',
 'FI',
 'FI',
 'DS',
 'DS',
 'DS',
 'DLA',
 'PBB',
 'CVA',
 'BDA',
 'BDA',
 'BDA',
 'BDA',
 'FTS',
 'WR',
 'HLP',
 'BM',
 'FIC',
 'FP',
 'BDS',
 'BDS',
 'CVA',
 'BM',
 'OP',
 'WHS',
 'WHS',
 'WHN',
 'WHN',
 'AIS',
 'BM',
 'TPMS',
 'TPMS',
 'TPMS',
 'CS-弹簧',
 'CS-弹簧',
 'OIP',
 'TFM',
 'ASV',
 'BPS',
 'HCR',
 'KS',
 'ACH',
 'HCR',
 'CA',
 'ICK',
 'ACC',
 'ACC',
 'CON',
 'CON',
 'CON',
 'ICK',
 'ICK',
 'ALT',
 'ALT',
 'STR',
 'PST',
 'STR',
 'STR',
 'EMD',
 'EMD',
 'CA',
 'CA',
 'CA',
 'EMD',
 'AS',
 'CON',
 'CA',
 'CON',
 'CON',
 'CON',
 'ACH',
 'MEM',
 'CPA',
 'ALT',
 'EPE',
 'APT',
 'ITC',
 'ITC',
 'FP',
 'OS',
 'OS',
 'BMC',
 'CA',
 'PSH',
 'RAD',
 'RAD',
 'RAD',
 'ITC',
 'BM',
 'CA',
 'PSH',
 'SPW',
 'PSH',
 'PSH',
 'RAD',
 'RAD',
 'EM',
 'HB',
 'HB',
 'PSH',
 'AST',
 'SPW',
 'SPW',
 'CA',
 'WM',
 'SA',
 'SA',
 'SA',
 'SA',
 'SA',
 'BMR',
 'CVA',
 'TCK',
 'TF',
 'BHH',
 'BHH',
 'BHH',
 'BHH',
 'TMS',
 'FSU',
 'FI',
 'FI',
 'BHH',
 'BHH',
 'MI',
 'MI',
 'BHH',
 'BHH',
 'FI',
 'BHH',
 'BHH',
 'EAF',
 'EAF',
 'EAF',
 'EAF',
 'EAF',
 'EAF',
 'DS',
 'BHH',
 'BHH',
 'BHH',
 'BHH',
 'AEC',
 'SA',
 'BHH',
 'BHH',
 'BHH',
 'CAF',
 'CAF',
 'EAF',
 'SG',
 'ICK',
 'FI',
 'CAF',
 'TGK',
 'DIF',
 'CAF',
 'EAF',
 'FF',
 'PSR',
 'PSR',
 'CPS',
 'DS',
 'DS',
 'PSP',
 'SCS',
 'ET',
 'BM',
 'BBC',
 'CA',
 'HLS',
 'ET',
 'GS',
 ...]

In [29]:
df_m = df_mrp
df_m['品类'] = hebe
df_m[df_m.loc[:, '品类'] == 'CA']

                SKU  品类     层级  身份   负责人
156      USCAKMB010  CA   TOP1  老品  Hebe
200    USCAK20011-C  CA     普通  老品  Hebe
306    USCAK12177-C  CA     普通  老品  Hebe
311    USCAK20585-C  CA     普通  老品  Hebe
361     USCA26767LR  CA   TOP1  老品  Hebe
...             ...  ..    ...  ..   ...
55614  USSBK27303-C  CA  TOP20  新品  Hebe
55615  USSBK27701-C  CA  TOP20  新品  Hebe
55616  USSBR33239-C  CA  TOP20  新品  Hebe
55871  USSBK27304-C  CA  TOP20  新品  Hebe
56367  USCAK21597LR  CA     普通  新品  Hebe

[4866 rows x 5 columns]

In [30]:
# 筛选Hebe负责的品类
df_m = df_m[(df_m.loc[:,'负责人']=='Hebe') | (df_m.loc[:, '品类']=='CA')].reset_index(drop=True)
df_m

                     SKU     品类     层级    身份   负责人
0         USABS47900C1-C    ABS  TOP20    老品  Hebe
1        USBCB72928BLR-C     BC   TOP1    老品  Hebe
2            USCS81280-C  CS-弹簧  TOP10  断货成长  Hebe
3           USABS25870-C    ABS   TOP1    老品  Hebe
4            USABS5570-C    ABS  TOP10    老品  Hebe
...                  ...    ...    ...   ...   ...
24393  USWSP65508B1-4-YC    WSP  TOP10    新品  Hebe
24394  USWSP65508B1-2-YC    WSP     普通    新品  Hebe
24395  USWSP54521B1-4-YC    WSP  TOP20    新品  Hebe
24396  USWSP54717B1-4-YC    WSP     普通    新品  Hebe
24397  USWSP54717B1-2-YC    WSP     普通    新品  Hebe

[24398 rows x 5 columns]

In [31]:
# 将负责人为NaN的转为Hebe
df_m['负责人'] = df_m['负责人'].map(lambda x : 'Hebe')

df_m

                     SKU     品类     层级    身份   负责人
0         USABS47900C1-C    ABS  TOP20    老品  Hebe
1        USBCB72928BLR-C     BC   TOP1    老品  Hebe
2            USCS81280-C  CS-弹簧  TOP10  断货成长  Hebe
3           USABS25870-C    ABS   TOP1    老品  Hebe
4            USABS5570-C    ABS  TOP10    老品  Hebe
...                  ...    ...    ...   ...   ...
24393  USWSP65508B1-4-YC    WSP  TOP10    新品  Hebe
24394  USWSP65508B1-2-YC    WSP     普通    新品  Hebe
24395  USWSP54521B1-4-YC    WSP  TOP20    新品  Hebe
24396  USWSP54717B1-4-YC    WSP     普通    新品  Hebe
24397  USWSP54717B1-2-YC    WSP     普通    新品  Hebe

[24398 rows x 5 columns]

In [32]:
# 与position左连接，去重复行
df_m_position = pd.merge(left=df_m, right=df_position, how='left', left_on='SKU', right_on='SKU').fillna({'YKD库存':0, 'row':''}).fillna('')

print(list(df_m_position.columns))
df_m_position

['SKU', '品类', '层级', '身份', '负责人', '在途总数', 'YKD库存', 'row']

                     SKU     品类     层级    身份   负责人   在途总数  YKD库存    row
0         USABS47900C1-C    ABS  TOP20    老品  Hebe   37.0   19.0  38679
1        USBCB72928BLR-C     BC   TOP1    老品  Hebe  154.0   67.0  16743
2            USCS81280-C  CS-弹簧  TOP10  断货成长  Hebe   21.0    2.0  11000
3           USABS25870-C    ABS   TOP1    老品  Hebe  101.0   14.0  38624
4            USABS5570-C    ABS  TOP10    老品  Hebe   75.0   32.0  38629
...                  ...    ...    ...   ...   ...    ...    ...    ...
24393  USWSP65508B1-4-YC    WSP  TOP10    新品  Hebe           0.0
24394  USWSP65508B1-2-YC    WSP     普通    新品  Hebe           0.0
24395  USWSP54521B1-4-YC    WSP  TOP20    新品  Hebe           0.0
24396  USWSP54717B1-4-YC    WSP     普通    新品  Hebe           0.0
24397  USWSP54717B1-2-YC    WSP     普通    新品  Hebe           0.0

[24398 rows x 8 columns]

In [33]:
# 获得MRP表的数据
df_m_position = pd.merge(left=df_m_position, right=df_stock, how='left', left_on='SKU', right_on='SKU', suffixes=('_position', '')).fillna(0)
df_m_position

,SKU,品类,层级,身份,负责人,在途总数,YKD库存_position,row,组合料库存,YKD库存,总库存
0,USABS47900C1-C,ABS,TOP20,老品,Hebe,37.0,19.0,38679,0.0,19.0,19.0
1,USBCB72928BLR-C,BC,TOP1,老品,Hebe,154.0,67.0,16743,2.0,67.0,69.0
2,USCS81280-C,CS-弹簧,TOP10,断货成长,Hebe,21.0,2.0,11000,0.0,2.0,2.0
3,USABS25870-C,ABS,TOP1,老品,Hebe,101.0,14.0,38624,0.0,14.0,14.0
4,USABS5570-C,ABS,TOP10,老品,Hebe,75.0,32.0,38629,0.0,32.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...
24393,USWSP65508B1-4-YC,WSP,TOP10,新品,Hebe,,0.0,,0.0,0.0,0.0
24394,USWSP65508B1-2-YC,WSP,普通,新品,Hebe,,0.0,,0.0,0.0,0.0
24395,USWSP54521B1-4-YC,WSP,TOP20,新品,Hebe,,0.0,,0.0,0.0,0.0
24396,USWSP54717B1-4-YC,WSP,普通,新品,Hebe,,0.0,,0.0,0.0,0.0
24397,USWSP54717B1-2-YC,WSP,普通,新品,Hebe,,0.0,,0.0,0.0,0.0

In [34]:
df_mrp = df_m_position[['SKU', 
                        '品类',
                        '层级',
                        '身份',
                        'row']].copy()

df_mrp

                     SKU     品类     层级    身份    row
0         USABS47900C1-C    ABS  TOP20    老品  38679
1        USBCB72928BLR-C     BC   TOP1    老品  16743
2            USCS81280-C  CS-弹簧  TOP10  断货成长  11000
3           USABS25870-C    ABS   TOP1    老品  38624
4            USABS5570-C    ABS  TOP10    老品  38629
...                  ...    ...    ...   ...    ...
24393  USWSP65508B1-4-YC    WSP  TOP10    新品
24394  USWSP65508B1-2-YC    WSP     普通    新品
24395  USWSP54521B1-4-YC    WSP  TOP20    新品
24396  USWSP54717B1-4-YC    WSP     普通    新品
24397  USWSP54717B1-2-YC    WSP     普通    新品

[24398 rows x 5 columns]

# 5.基础整合

In [35]:
# df_last = pd.read_excel(last,
#                         header=1,
#                         usecols='C,D,U,V,X:AI,AK:AL,AO,AP,AS').fillna('')

df_last = pd.read_excel(last,
                        header=1,
                        usecols='B,C,I:V,X:Y,AB:AC').fillna('')

df_update = pd.read_excel(update,
                          header=0)

df_day_category = pd.read_excel(day_category,
                                names=['SKU', '调价记录'],
                                usecols='A,B').fillna('')

df_last['原始行号'] = [i+3 for i in range(len(df_last))]

print(df_last.columns)
df_last

Index([                  'SKU',                   '替代料',
                        '实时库存',                 '组合料库存',
                       'YKD库存',     2023-08-25 00:00:01,
           2023-08-24 00:00:01,     2023-08-23 00:00:01,
       '2023-08-25 00:00:01.1', '2023-08-24 00:00:01.1',
       '2023-08-23 00:00:01.1',     2023-08-22 00:00:01,
           2023-08-21 00:00:01,     2023-08-20 00:00:01,
           2023-08-19 00:00:01,     2023-08-18 00:00:01,
                        '改价记录',                  '断货时间',
                     '总品类调价记录',                '每日调价记录',
                        '原始行号'],
      dtype='object')

,SKU,替代料,实时库存,组合料库存,YKD库存,2023-08-25 00:00:01,2023-08-24 00:00:01,2023-08-23 00:00:01,2023-08-25 00:00:01.1,2023-08-24 00:00:01.1,...,2023-08-22 00:00:01,2023-08-21 00:00:01,2023-08-20 00:00:01,2023-08-19 00:00:01,2023-08-18 00:00:01,改价记录,断货时间,总品类调价记录,每日调价记录,原始行号
0,USBCB72928BLR-C,USBCB72928BLR,69.0,2.0,69.0,69.0,72.0,77.0,1.0,3.0,...,3.0,0.0,0.0,2.0,3.0,,,,,3
1,USPSP14045D-C,USPSP14045D,48.0,0.0,48.0,49.0,43.0,45.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,,,2.7-T3,,4
2,USBCB75352ZLR-C,USBCB75352ZLR,2.0,0.0,2.0,2.0,2.0,4.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,8.24-T10,,,,5
3,USBCB08180ZLR-C,USBCB08180ZLR,102.0,12.0,102.0,103.0,90.0,90.0,1.0,1.0,...,0.0,0.0,1.0,1.0,1.0,,,6.5-J2,,6
4,USPSP01008D-C,USPSP01008D,19.0,0.0,19.0,19.0,19.0,19.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,,,,,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24394,USCAK10052-C,,57.0,0.0,57.0,,,,,,...,,,,,,,,,,24397
24395,USCA01113-C,,3.0,0.0,3.0,,,,,,...,,,,,,,,,,24398
24396,USCA01114-C,,6.0,0.0,6.0,,,,,,...,,,,,,,,,,24399
24397,USCAK09028-C,,4.0,3.0,4.0,,,,,,...,,,,,,,,,,24400
24398,USBRR54064LR,,0.0,0.0,0.0,,,,,,...,,,,,,,,,,24401

In [36]:
if timing == 'am':
    df_l = df_last[['SKU', '替代料'] + list(df_last.columns[4:6+1]) + list(df_last.columns[8:14+1]) + [ '改价记录',
                                                                                                         '断货时间',
                                                                                                         '总品类调价记录',
                                                                                                         '每日调价记录',
                                                                                                         '原始行号']].copy()
    df_l.columns = list(df_l.columns[:2]) + ['库存date'] + list(df_l.columns[3:])

else:
    df_l = df_last[['SKU', '替代料'] + list(df_last.columns[5:15+1]) + ['改价记录',
                                                                         '断货时间',
                                                                         '总品类调价记录',
                                                                         '每日调价记录',
                                                                         '原始行号']].copy()

print(list(df_l.columns))
# df_l

['SKU', '替代料', '库存date', datetime.datetime(2023, 8, 25, 0, 0, 1), datetime.datetime(2023, 8, 24, 0, 0, 1), '2023-08-25 00:00:01.1', '2023-08-24 00:00:01.1', '2023-08-23 00:00:01.1', datetime.datetime(2023, 8, 22, 0, 0, 1), datetime.datetime(2023, 8, 21, 0, 0, 1), datetime.datetime(2023, 8, 20, 0, 0, 1), datetime.datetime(2023, 8, 19, 0, 0, 1), '改价记录', '断货时间', '总品类调价记录', '每日调价记录', '原始行号']

In [37]:
df_position = df_position[['SKU', 'YKD库存', 'row']]
merge_df_update = df_l
merge_df_update['note'] = ''

In [38]:
# MRP表有的SKU，断货改价表没有的，添加到断货改价表里
list_sku_note = df_mrp[~df_mrp['SKU'].isin(merge_df_update['SKU'])]['SKU'].tolist()
print(len(list_sku_note))
print(list_sku_note)

6
['USCAK10009-C', 'USBCB92640-C', 'USCA22557', 'USCA22558', 'USCAK22557LR', 'USBRR54064']

In [39]:
# MRP表有的SKU，断货改价表没有的，添加到断货改价表里
df_last_list = merge_df_update['SKU'].tolist()
length = len(merge_df_update)

for i in range(len(list_sku_note)):
    if list_sku_note[i] in df_last_list:
        merge_df_update.loc[df_last_list.index(list_sku_note[i]), 'note'] = 'last'
    else:
        merge_df_update.loc[length, 'note'] = 'mrp'
        merge_df_update.loc[length, 'SKU'] = list_sku_note[i]
        length += 1
        
merge_df_update = merge_df_update.fillna('')
merge_df_update

,SKU,替代料,库存date,2023-08-25 00:00:01,2023-08-24 00:00:01,2023-08-25 00:00:01.1,2023-08-24 00:00:01.1,2023-08-23 00:00:01.1,2023-08-22 00:00:01,2023-08-21 00:00:01,2023-08-20 00:00:01,2023-08-19 00:00:01,改价记录,断货时间,总品类调价记录,每日调价记录,原始行号,note
0,USBCB72928BLR-C,USBCB72928BLR,69.0,69.0,72.0,1.0,3.0,3.0,3.0,0.0,0.0,2.0,,,,,3.0,
1,USPSP14045D-C,USPSP14045D,48.0,49.0,43.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,,,2.7-T3,,4.0,
2,USBCB75352ZLR-C,USBCB75352ZLR,2.0,2.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,8.24-T10,,,,5.0,
3,USBCB08180ZLR-C,USBCB08180ZLR,102.0,103.0,90.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,,,6.5-J2,,6.0,
4,USPSP01008D-C,USPSP01008D,19.0,19.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,,,,7.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24400,USBCB92640-C,,,,,,,,,,,,,,,,,mrp
24401,USCA22557,,,,,,,,,,,,,,,,,mrp
24402,USCA22558,,,,,,,,,,,,,,,,,mrp
24403,USCAK22557LR,,,,,,,,,,,,,,,,,mrp
24404,USBRR54064,,,,,,,,,,,,,,,,,mrp

In [40]:
merge_df_update = pd.merge(left=merge_df_update, right=df_position, how='left', left_on='SKU', right_on='SKU', suffixes=('_position','')).fillna('')

print(list(merge_df_update.columns))
merge_df_update

['SKU', '替代料', '库存date', datetime.datetime(2023, 8, 25, 0, 0, 1), datetime.datetime(2023, 8, 24, 0, 0, 1), '2023-08-25 00:00:01.1', '2023-08-24 00:00:01.1', '2023-08-23 00:00:01.1', datetime.datetime(2023, 8, 22, 0, 0, 1), datetime.datetime(2023, 8, 21, 0, 0, 1), datetime.datetime(2023, 8, 20, 0, 0, 1), datetime.datetime(2023, 8, 19, 0, 0, 1), '改价记录', '断货时间', '总品类调价记录', '每日调价记录', '原始行号', 'note', 'YKD库存', 'row']

,SKU,替代料,库存date,2023-08-25 00:00:01,2023-08-24 00:00:01,2023-08-25 00:00:01.1,2023-08-24 00:00:01.1,2023-08-23 00:00:01.1,2023-08-22 00:00:01,2023-08-21 00:00:01,2023-08-20 00:00:01,2023-08-19 00:00:01,改价记录,断货时间,总品类调价记录,每日调价记录,原始行号,note,YKD库存,row
0,USBCB72928BLR-C,USBCB72928BLR,69.0,69.0,72.0,1.0,3.0,3.0,3.0,0.0,0.0,2.0,,,,,3.0,,67.0,16743
1,USPSP14045D-C,USPSP14045D,48.0,49.0,43.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,,,2.7-T3,,4.0,,48.0,15819
2,USBCB75352ZLR-C,USBCB75352ZLR,2.0,2.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,8.24-T10,,,,5.0,,2.0,16765
3,USBCB08180ZLR-C,USBCB08180ZLR,102.0,103.0,90.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,,,6.5-J2,,6.0,,102.0,16746
4,USPSP01008D-C,USPSP01008D,19.0,19.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,,,,7.0,,19.0,16192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24400,USBCB92640-C,,,,,,,,,,,,,,,,,mrp,9.0,17407
24401,USCA22557,,,,,,,,,,,,,,,,,mrp,3.0,34146
24402,USCA22558,,,,,,,,,,,,,,,,,mrp,6.0,34147
24403,USCAK22557LR,,,,,,,,,,,,,,,,,mrp,4.0,30399
24404,USBRR54064,,,,,,,,,,,,,,,,,mrp,2.0,36267

In [ ]:
merge_df_update[merge_df_update.loc[:,'SKU']=='USBCB92640-C']
merge_df_update[merge_df_update.loc[:,'SKU']=='USBCB92640']
print(merge_df_update[merge_df_update.loc[:,'SKU']=='USCAK10052-C'])
merge_df_update[merge_df_update.loc[:,'SKU']=='USCAK10009-C']

In [ ]:
merge_df_update = pd.merge(left=merge_df_update, right=df_mrp, how='left', left_on='SKU', right_on='SKU', suffixes=('','_mrp'))

print(merge_df_update.columns)
# merge_df_update

In [ ]:
merge_df_update = merge_df_update.merge(df_stock_way, left_on='SKU', right_on='SKU', how='left')

print(list(merge_df_update.columns))
merge_df_update

In [ ]:
merge_df_update = pd.merge(left=merge_df_update, right=df_stock, how='left', left_on='SKU',right_on='SKU', suffixes=('', '_stock'))
merge_df_update['YKD库存'] = merge_df_update['YKD库存_stock']
print(merge_df_update.columns)
merge_df_update

In [ ]:
# 与替代料匹配更新SKU
merge_df = merge_df_update.merge(df_update, left_on='SKU', right_on='替代料', how='left', suffixes=('','_x')).fillna('')

# 更新SKU
if '替代料_x' in merge_df.columns:
    merge_df['SKU'] = merge_df.apply(lambda row: row['SKU'] if row['替代料_x']=='' else row['主料SKU'], axis=1)
    
    merge_df.drop(columns=['替代料_x', '主料SKU'], inplace=True)
    
print(list(merge_df.columns))
merge_df

In [ ]:
merge_df,l = DEduplicate(merge_df)

In [ ]:
merge_df[merge_df.loc[:,'SKU']=='USCAK10052-C']['note']
# merge_df[merge_df.loc[:,'SKU']=='USCAK10009-C']

In [ ]:
df = merge_df
df['改价'] = ''
df['weekly_sale'] = ''
df['改价+断货'] = ''
df['总品类调价记录_2'] = ''
df['合计改价记录'] = ''

if timing == 'am':
    df = df[['层级',
             'SKU',
             '替代料',
             '品类',
             '身份',
             '在途总数',
             '改价',
             '组合料库存',
             'YKD库存'] + list(df.columns)[2:11+1] + ['weekly_sale',
                                                       '改价记录', 
                                                       '断货时间', 
                                                       '改价+断货',
                                                       '总库存',
                                                       '总品类调价记录',
                                                       '每日调价记录',
                                                       '总品类调价记录_2',
                                                       '合计改价记录',
                                                       'note',
                                                       '原始行号',
                                                       'row']].copy()
else:
    df = df[['层级',
             'SKU',
             '替代料',
             '品类',
             '身份',
             '在途总数',
             '改价',
             '组合料库存',
             'YKD库存'] + list(df.columns)[2:12+1] + ['weekly_sale',
                                                       '改价记录', 
                                                       '断货时间', 
                                                       '改价+断货',
                                                       '总库存',
                                                       '总品类调价记录',
                                                       '每日调价记录',
                                                       '总品类调价记录_2',
                                                       '合计改价记录',
                                                       'note',
                                                       '原始行号',
                                                       'row']].copy()
print(list(df.columns))
df

# 6.其他信息

In [ ]:
df_missing = pd.read_excel(stcok,
                           sheet_name=1,
                           names=['SKU', '无Record ID'],
                           usecols='D,F')

df_missing = df_missing.groupby('SKU', as_index=False).sum()

df_missing

In [ ]:
df = pd.merge(left=df, right=df_missing, how='left', left_on='SKU', right_on='SKU').fillna(0)

print(list(df.columns))
df

In [ ]:
df_missing = pd.merge(left=df_missing, right=df_position, how='left', left_on='SKU', right_on='SKU').fillna('')
df_missing = df_missing[df_missing.loc[:,'row'] != ''][['SKU', '无Record ID']].copy()
df_missing = df_missing.groupby('SKU', as_index=False).sum()
df_missing

In [ ]:
df = pd.merge(left=df, right=df_missing, how='left', left_on='SKU', right_on='SKU', suffixes=('_missing1', '_missing2')).fillna('')

print(df.columns)
df

In [ ]:
df.columns

In [ ]:
df['无Record ID'] = [df.loc[i,'无Record ID_missing2'] if df.loc[i,'无Record ID_missing2'] != '' else df.loc[i,'无Record ID_missing1'] for i in range(len(df))]
df['无Record ID'] = pd.to_numeric(df['无Record ID'], errors='coerce')
df[ 'YKD库存'] = pd.to_numeric(df['YKD库存'], errors='coerce')
df['总库存'] = pd.to_numeric(df['总库存'], errors='coerce')
df['实时库存'] = [df.loc[i, 'YKD库存'] - df.loc[i, '无Record ID'] if df.loc[i, 'note'] != 'last' else '' for i in range(len(df))]
df.loc[:,'总库存'] = df.loc[:, '总库存'] - df.loc[:, '无Record ID']
print(list(df.columns))
df

In [ ]:
df_tmp = df
if timing == 'am':
    df_tmp = df_tmp[['层级',
             'SKU',
             '替代料',
             '品类',
             '身份',
             '在途总数',
             '改价',
             '无Record ID',
             '实时库存',
             '组合料库存',
             'YKD库存'] + list(df_tmp.columns)[9:18+1] + ['weekly_sale',
                                                       '改价记录', 
                                                       '断货时间', 
                                                       '改价+断货',
                                                       '总库存',
                                                       '总品类调价记录',
                                                       '每日调价记录',
                                                       '总品类调价记录_2',
                                                       '合计改价记录',
                                                       'note',
                                                       '原始行号',
                                                       'row']].copy()
else:
    df_tmp = df_tmp[['层级',
             'SKU',
             '替代料',
             '品类',
             '身份',
             '在途总数',
             '改价',
             '无Record ID',
             '实时库存',
             '组合料库存',
             'YKD库存'] + list(df_tmp.columns)[9:19+1] + ['weekly_sale',
                                                       '改价记录', 
                                                       '断货时间', 
                                                       '改价+断货',
                                                       '总库存',
                                                       '总品类调价记录',
                                                       '每日调价记录',
                                                       '总品类调价记录_2',
                                                       '合计改价记录',
                                                       'note',
                                                       '原始行号',
                                                       'row']].copy()
print(list(df_tmp.columns))
df = df_tmp
df

In [ ]:
if timing == 'am':
    df_sales = pd.read_excel(stcok,
                             sheet_name=2,
                             usecols='D,F')
    
    df_sales = df_sales.groupby('SKU', as_index=False).sum()

In [ ]:
if timing == 'am':
    df = pd.merge(left=df, right=df_sales, how='left', left_on='SKU', right_on='SKU', suffixes=('','_sales')).fillna(0)

In [ ]:
if timing == 'am':
    df_sales = pd.merge(left=df_sales, right=df_position, how='left', left_on='SKU', right_on='SKU', suffixes=('_x','')).fillna('')
    df_sales = df_sales[df_sales['row'] != ''][['购买数量', 'row']].copy()
    df_sales = df_sales.groupby('row', as_index=False).sum()
    df_sales

In [ ]:
if timing == 'am':
#     df_tmp = df
    df = pd.merge(left=df, right=df_sales, how='left', left_on='row', right_on='row', suffixes=('_sales1', '_sales2')).fillna('')
    df['销量date'] = [df.loc[i, '购买数量_sales2'] if df.loc[i, '购买数量_sales2'] != '' else df.loc[i, '购买数量_sales1']  for i in range(len(df))]
    print(list(df.columns))
    
    df

In [ ]:
if timing == 'am':
    df = df[['层级',
             'SKU',
             '替代料',
             '品类',
             '身份',
             '在途总数',
             '改价',
             '无Record ID',
             '实时库存',
             '组合料库存',
             'YKD库存'] + list(df.columns)[11:13+1]+ ['销量date'] + list(df.columns)[14:20+1] + ['weekly_sale',
                                                                                                 '改价记录', 
                                                                                                 '断货时间', 
                                                                                                 '改价+断货',
                                                                                                 '总库存',
                                                                                                 '总品类调价记录',
                                                                                                 '每日调价记录',
                                                                                                 '总品类调价记录_2',
                                                                                                 '合计改价记录',
                                                                                                 'note',
                                                                                                 '原始行号']].copy()

print(list(df.columns))
df

In [ ]:
offset = 3

df['改价'] = ['=IFERROR(IF(I' + str(i+3) + '-$L' + str(i+3) + '>0,"海运上架",IF(I'+ str(i+3) + '<=0,"断货","")),"")' for i in range(len(df))]
df['weekly_sale'] = ['=SUM(O' + str(i+3) + ':V' + str(i+3) +')' for i in range(len(df))]
df['改价+断货'] = [ '=TEXTJOIN(";",1,X' + str(i+3) + ',Y' + str(i+3) + ')' for i in range(len(df))]
df['总品类调价记录_2'] = ['=TEXTJOIN(";",TRUE,AB' + str(i+3) + ':AC' + str(i+3) + ')' for i in range(len(df))]
df['合计改价记录'] = ['=TEXTJOIN(";",1,AD' + str(i+3) + ',X' + str(i+3) + ')' for i in range(len(df))]

In [ ]:
print(df.columns)

In [ ]:
df_tmp = df
df_tmp = pd.merge(left=df_tmp, right=df_day_category, how='left', left_on='SKU', right_on='SKU', suffixes=('','_last_record')).fillna('')
df_tmp['每日调价记录'] = df_tmp['调价记录']
print(df_tmp.columns)
# df_tmp

In [ ]:
# df = df_tmp

if timing == 'am':
    df_tmp = df_tmp[['层级',
                     'SKU',
                     '替代料',
                     '品类',
                     '身份',
                     '在途总数',
                     '改价',
                     '无Record ID',
                     '实时库存',
                     '组合料库存',
                     'YKD库存'] + list(df_tmp.columns)[11:21+1] + ['weekly_sale',
                                                                     '改价记录', 
                                                                     '断货时间', 
                                                                     '改价+断货',
                                                                     '总库存',
                                                                     '总品类调价记录',
                                                                     '每日调价记录',
                                                                     '总品类调价记录_2',
                                                                     '合计改价记录',
                                                                     'note',
                                                                     '原始行号']].copy()

    print(list(df_tmp.columns))
    df_tmp
else:
    df_tmp = df_tmp[['层级',
                     'SKU',
                     '替代料',
                     '品类',
                     '身份',
                     '在途总数',
                     '改价',
                     '无Record ID',
                     '实时库存',
                     '组合料库存',
                     'YKD库存'] + list(df_tmp.columns)[11:21+1] + ['weekly_sale',
                                                                     '改价记录', 
                                                                     '断货时间', 
                                                                     '改价+断货',
                                                                     '总库存',
                                                                     '总品类调价记录',
                                                                     '每日调价记录',
                                                                     '总品类调价记录_2',
                                                                     '合计改价记录',
                                                                     'note',
                                                                     '原始行号']].copy()
# df = df_tmp
print(df_tmp.columns)
df_tmp

In [ ]:
df_tmp.columns

In [ ]:
df = df_tmp

In [ ]:
from datetime import datetime

now = datetime.now()
month = now.month
day = now.day
month_day = f'{month}.{day}'

if timing == 'am':
    out = 'Bear_断货改价_Hebe_上午 ' + month_day + '.xlsx'
else:
    out = 'Bear_断货改价_Hebe_下午 ' + month_day + '.xlsx'

df.to_excel('./' + out, 
            index=False ,
            startrow=1)

# 7.改格式

In [ ]:
from openpyxl import load_workbook

In [ ]:
wb_last = load_workbook(last)
ws_last = wb_last.worksheets[0]
ws_last

In [ ]:
wb_out = load_workbook('./' + out)
ws_out = wb_out.worksheets[0]

In [ ]:
coef = 1.125
ws_out.column_dimensions['A'].width = coef * 5.56
ws_out.column_dimensions['B'].width = coef * 18.69
ws_out.column_dimensions['C'].width = coef * 18.69
ws_out.column_dimensions['D'].width = coef * 6.88
ws_out.column_dimensions['E'].width = coef * 6.88
ws_out.column_dimensions['F'].width = coef * 9.88
ws_out.column_dimensions['G'].width = coef * 6.88
ws_out.column_dimensions['H'].width = coef * 9.88
ws_out.column_dimensions['I'].width = coef * 9.88
ws_out.column_dimensions['J'].width = coef * 7.04
ws_out.column_dimensions['K'].width = coef * 5.5
ws_out.column_dimensions['L'].width = coef * 5.5
ws_out.column_dimensions['M'].width = coef * 5.5
ws_out.column_dimensions['N'].width = coef * 5.5
ws_out.column_dimensions['O'].width = coef * 5.5
ws_out.column_dimensions['P'].width = coef * 5.5
ws_out.column_dimensions['Q'].width = coef * 5.5
ws_out.column_dimensions['R'].width = coef * 5.5
ws_out.column_dimensions['S'].width = coef * 5.5
ws_out.column_dimensions['T'].width = coef * 5.5
ws_out.column_dimensions['U'].width = coef * 5.5
ws_out.column_dimensions['V'].width = coef * 5.5
ws_out.column_dimensions['W'].width = coef * 5.5
ws_out.column_dimensions['X'].width = coef * 10.88
ws_out.column_dimensions['Y'].width = coef * 13
ws_out.column_dimensions['Z'].width = coef * 10.88
ws_out.column_dimensions['AA'].width = coef * 10.88
ws_out.column_dimensions['AB'].width = coef * 13
ws_out.column_dimensions['AC'].width = coef * 10.88
ws_out.column_dimensions['AD'].width = coef * 10.88
ws_out.column_dimensions['AE'].width = coef * 10.88
ws_out.column_dimensions['AF'].width = coef * 8.75
ws_out.column_dimensions['AG'].width = coef * 8.75

ws_out.row_dimensions[1].height = 25
ws_out.row_dimensions[2].height = 34
for i in range(3, ws_out.max_row+1):
    ws_out.row_dimensions[i].height = 16.5

In [ ]:
from openpyxl.styles import Font, PatternFill
from openpyxl.styles import *
import datetime

In [ ]:
orange ='00FFCC99'
blue_dark = 'FF8DB4E2'
green = 'FF92D050'
yellow = '00FFFF00'

now = datetime.datetime.now()
month = now.month
day = now.day
month_day = f'{month}/{day}'

ws_out['A1'].value = month_day
ws_out['A1'].font = Font(bold=True)

ws_out.merge_cells('B1:E1')

ws_out['G1'].value = '任务栏'

ws_out.merge_cells('H1:K1')

ws_out['O1'].value = '近一周销量'
ws_out.merge_cells('O1:V1')

ws_out['X1'].value = '10.5-J310.18-T6(日期最新在后面）'

In [ ]:
ws_out['AA2'].fill = PatternFill(patternType='solid', fgColor=yellow)

for i in ws_out['A2:J2']:
    for j in i:
        j.fill = PatternFill(patternType='solid', fgColor=blue_dark)
        
for i in ws_out['K2:N2']:
    for j in i:
        j.fill = PatternFill(patternType='solid', fgColor=green)

for i in ws_out['O2:V2']:
    for j in i:
        j.fill = PatternFill(patternType='solid', fgColor=orange)
         
for i in ws_out['W2:Z2']:
    for j in i:
        j.fill = PatternFill(patternType='solid', fgColor=blue_dark)
        
for i in ws_out['AB2:AH2']:
    for j in i:
        j.fill = PatternFill(patternType='solid', fgColor=blue_dark)
        
for i in ws_out['M2:N2']:
    for j in i:
        j.value = datetime.datetime.strptime(str(j.value)[:17] + '01', '%Y-%m-%d %H:%M:%S')
        j.number_format = 'm/d;@'
        
for i in ws_out['P2:V2']:
    for j in i:
        j.value = datetime.datetime.strptime(str(j.value)[:17] + '01', '%Y-%m-%d %H:%M:%S')
        j.number_format = 'm/d;@'
#         j.fill = PatternFill(patternType='solid', fgColor=blue_light)

In [ ]:
# for i in range(3, ws_out.max_row+1):
#     row = ws_out['AH'+str(i)].value
#     if row != None:
#         if timing == 'am':
#             color_C = ws_last['D'+str(row)].font.color
#             color_N = ws_last['Z'+str(row)].font.color
#             color_M = ws_last['Y'+str(row)].font.color
#             color_L = ws_last['X'+str(row)].font.color
#             color_K = ws_last['X'+str(row)].font.color

#         else:
#             color_C = ws_last['D'+str(row)].font.color
#             color_N = ws_last['AA'+str(row)].font.color
#             color_M = ws_last['Z'+str(row)].font.color
#             color_L = ws_last['Y'+str(row)].font.color
#             color_K = ws_last['X'+str(row)].font.color

#     else:
#         color_C = None
#         color_N = None
#         color_M = None
#         color_L = None
#         color_K = None
    
#     if color_C != None:
#         color_C = color_C.rgb
#     else:
#         color_C = None  
    
#     if color_N != None:
#         color_N = color_N.rgb
#     else:
#         color_N = None
    
#     if color_M != None:
#         color_M = color_M.rgb
#     else:
#         color_M = None

#     if color_L != None:
#         color_L = color_L.rgb
#     else:
#         color_L = None
    
#     if color_K != None:
#         color_K = color_K.rgb
#     else:
#         color_K = None
        

# #     print(i,color_C,color_N, color_M, color_L, color_K)

#     if type(color_C) == str:
#         ws_out['C'+str(i)].font = Font(color=color_C)
    
#     if type(color_N) == str:
#         ws_out['N'+str(i)].font = Font(color=color_N)
    
#     if type(color_M) == str:
#         ws_out['M'+str(i)].font = Font(color=color_M)

#     if type(color_L) == str:
#         ws_out['L'+str(i)].font = Font(color=color_L)
        
#     if type(color_K) == str:
#         ws_out['K'+str(i)].font = Font(color=color_K)

In [ ]:

for i in range(3, ws_out.max_row+1):
    row = ws_out['AH'+str(i)].value
    if row != None:
        if timing == 'am':
            color_C = ws_last['C'+str(row)].font.color
            color_N = ws_last['M'+str(row)].font.color
            color_M = ws_last['L'+str(row)].font.color
            color_L = ws_last['K'+str(row)].font.color
            color_K = ws_last['K'+str(row)].font.color

        else:
            color_C = ws_last['C'+str(row)].font.color
            color_N = ws_last['N'+str(row)].font.color
            color_M = ws_last['M'+str(row)].font.color
            color_L = ws_last['L'+str(row)].font.color
            color_K = ws_last['K'+str(row)].font.color
            
    else:
        color_C = None
        color_N = None
        color_M = None
        color_L = None
        color_K = None
    
    if color_C != None:
        color_C = color_C.rgb
    else:
        color_C = None  
    
    if color_N != None:
        color_N = color_N.rgb
    else:
        color_N = None
    
    if color_M != None:
        color_M = color_M.rgb
    else:
        color_M = None

    if color_L != None:
        color_L = color_L.rgb
    else:
        color_L = None
    
    if color_K != None:
        color_K = color_K.rgb
    else:
        color_K = None
        

#     print(i,color_C,color_N, color_M, color_L, color_K)

    if type(color_C) == str:
        ws_out['C'+str(i)].font = Font(color=color_C)
    
    if type(color_N) == str:
        ws_out['N'+str(i)].font = Font(color=color_N)
    
    if type(color_M) == str:
        ws_out['M'+str(i)].font = Font(color=color_M)

    if type(color_L) == str:
        ws_out['L'+str(i)].font = Font(color=color_L)
        
    if type(color_K) == str:
        ws_out['K'+str(i)].font = Font(color=color_K)

In [ ]:
from datetime import datetime
import time

In [ ]:
wb_out.save('./' + out.replace('Bear_', 'color_Bear_'))
time.sleep(3)
wb_out.close()
print(datetime.now())